### ISSUE TITLE
Huge vendors file

### ISSUE THREAD

**Issue by mrowa** [josephmbustamante/phaser3-typescript-starter-kit#13]
Hello @josephmbustamante ! Thanks for sharing this repository, I wouldn't be able to get phaser3 running so quickly with typescript and webpack without your code.

I have one problem - on clear repository I get 17MB vendors.app.bundle.js file. Do you know by any chance if this is some wrong configuration or is there a way around it? From what I understand, phaser3 by itself should only be ~6MB (and minimized around 1MB) and this is the only repository referenced in the app code.

**Comment by Danilotumix** [comment]
I think that's because the vendors.app.bundle.js created by webpack includes a lot of stuff only useful for development and debugging. I personally solved it by creating a new script for webpack (that I named "webpack.build.config.js") using the one provided here as a template, and deleting the "devtool" line and chaging the mode from "development" to "production". Also had to add a line on the "optimization" part so the resulting bundle had the name "vendors.app.bundle.js".

To run the build script, just edit the package.json and modify the build task so it uses the webpack config mean for production. In my case I edited it this way:

`"build": "webpack --config webpack.build.config.js",`

Finally, I run it with "npm run dev" or "yarn build" (I guess, if you use yarn) and it produces a 1.1 mb vendors.app.bundle.js that works as well as the one with all the dev stuff.

This is the "webpack.build.config.js" I used: [webpack.build.config.zip](https://github.com/josephmbustamante/phaser3-typescript-starter-kit/files/5099049/webpack.build.config.zip)


Not sure if this is the optimal or correct solution to this problem, tho.

**Comment by josephmbustamante** [comment]
@mrowa Thanks for mentioning this, and @Danilotumix thanks for providing a fix that worked for you.

I just updated the starter kit to work with TS 4.1 and Phaser 3.50, and in the process reconfigured the webpack config to look at the `NODE_ENV` environment variable and either do a production or development build depending on what is provided. The new vendors bundle is ~7mb for dev, and ~1mb for production, which is much more inline with what you would expect. Thanks to both of you!
